name: Conda build
on:
  push:
    branches:
    - master
  release:
    types:
    - created
  repository_dispatch:
    types:
    - conda-build

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build on Linux
    steps:
    - name: Login to GitHub Package Registry
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Docker image
      run: docker pull docker.pkg.github.com/sot/skare3/centos5-builder:latest
    - name: Build
      id: build
      run: >
        docker run --rm  --name builder -v $GITHUB_WORKSPACE:/github/workspace -w /github/workspace
        -e CONDA_PASSWORD -e GIT_USERNAME -e GIT_PASSWORD
        docker.pkg.github.com/sot/skare3/centos5-builder:latest
        ${GITHUB_REPOSITORY} --tag ${GITHUB_SHA}
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_USERNAME: chandra-xray
        GIT_PASSWORD: ${{ secrets.CHANDRA_XRAY_TOKEN }}
        GIT_ASKPASS: /home/aca/git_pass.py
    - uses: sot/skare3_tools/actions/gdrive_upload@master
      name: Upload to Google Drive
      with:
        files: |
          builds/linux-64
          builds/noarch
        directory: /ska3/conda-test
        options: --drive=cxc_ops
      env:
        GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}

