name: Release
on:
  release:
    types:
      - created

jobs:
  patch-release:
    runs-on: ubuntu-latest
    name: Patch Release
    steps:
    - name: Fetch Skare3 Tools
      uses: actions/checkout@v2
      with:
        repository: sot/skare3_tools
        ref: master
        path: skare3_tools
    - name: Release Description and Skare3 Issue
      run: |
        sudo -H pip3 install setuptools wheel
        sudo -H pip3 install -r ./skare3_tools/requirements.txt
        sudo -H pip3 install ./skare3_tools
        echo skare3-release-merge-info --user $GITHUB_ACTOR --repository $GITHUB_REPOSITORY --sha $GITHUB_SHA
        export GITHUB_PASSWORD=${{ secrets.GITHUB_TOKEN }}
        skare3-release-merge-info --user $GITHUB_ACTOR --repository $GITHUB_REPOSITORY --sha $GITHUB_SHA
        export GITHUB_PASSWORD=${{ secrets.CHANDRA_XRAY_TOKEN }}
        echo skare3-create-issue --user chandra-xray --repository sot/skare3 --latest-release $GITHUB_REPOSITORY --label 'Package update'
        skare3-create-issue --user chandra-xray --repository sot/skare3 --latest-release $GITHUB_REPOSITORY --label 'Package update'
        echo done
